# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboRealPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboRealPort.setGeometry(QtCore.QRect(10, 50, 150, 30))
        self.comboRealPort.setObjectName("comboRealPort")
        self.comboVirtPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboVirtPort.setGeometry(QtCore.QRect(210, 50, 150, 30))
        self.comboVirtPort.setObjectName("comboVirtPort")
        self.btnBoot = QtWidgets.QPushButton(self.centralwidget)
        self.btnBoot.setGeometry(QtCore.QRect(10, 90, 150, 30))
        self.btnBoot.setObjectName("btnBoot")
        self.btnStartFDT = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartFDT.setGeometry(QtCore.QRect(210, 90, 150, 30))
        self.btnStartFDT.setObjectName("btnStartFDT")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(20, 120, 191, 16))
        self.labelStatus.setObjectName("labelStatus")
        self.labelBaudrate = QtWidgets.QLabel(self.centralwidget)
        self.labelBaudrate.setGeometry(QtCore.QRect(230, 120, 161, 16))
        self.labelBaudrate.setObjectName("labelBaudrate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(10, 150, 381, 291))
        self.console.setObjectName("console")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 111, 20))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btnBoot.setText(_translate("MainWindow", "Boot Controller"))
        self.btnStartFDT.setText(_translate("MainWindow", "Start FDT"))
        self.labelStatus.setText(_translate("MainWindow", "Статус: Чакам"))
        self.labelBaudrate.setText(_translate("MainWindow", "Скорост: 9600 bps"))
        self.label.setText(_translate("MainWindow", "shema@abv.bg"))
        self.label_2.setText(_translate("MainWindow", "Реален порт"))
        self.label_3.setText(_translate("MainWindow", "Виртуални портове"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
